### ISSUE TITLE
Contao 4.11.9 - Internal Server Error

### ISSUE THREAD

**Issue by RWesemann** [Netzhirsch/CookieOptInBundle#12]
Netzhirsch Cookie Opt In Bundle Version: 2.7.14
Contao Version: 4.11.9 

Habe festgestellt, dass "Cookie Opt In Bundle" nicht korrekt funktioniert, nachdem Matomo seit 14 Tagen nichts mehr trackt. 
Bei Aufruf der Seite erhalte ich in der Console einen Internal Server Error: https://www.example.com/cookie/delete. 
Danach erscheint das "Privacy settings"-Overlay. Egal welche Auswahl ich dort vornehme, meine Einstellungen werden nicht übernommen. Bei Speichern erfolgt ein Ajax-Request auf https://www.example.com/cookie/allowed, ebenfalls mit einem Internal Server Error.
Das "Privacy settings"-Overlay erscheint immer auf jeder Seite.

**EDIT:**
Im Debug-Modus erhalte ich folgenden Fehler:
![image](https://user-images.githubusercontent.com/52671669/131254177-151b6644-d351-4259-9fea-cc418748dbc8.png)

**Comment by luhmannAlexander** [comment]
Danke für die Meldung. Ist mit Version 2.7.18 behoben.
