### ISSUE TITLE
Standard CSS laden wird nach jedem öffnen wieder aktiviert

### ISSUE THREAD

**Issue by FlorinvV** [Netzhirsch/CookieOptInBundle#13]
Wenn man die Checkbox "Standard-CSS laden" im Cookiebanner Modul deaktiviert und das Modul speichert, wird zwar das CSS auch nicht geladen, die Checkbox wird allerdings immer wieder aktiviert, wenn man in die Moduleinstellungen geht.

**Comment by luhmannAlexander** [comment]
Danke für die Meldung. Ist mit Version 2.7.18 behoben.
