### ISSUE TITLE
PageLayoutListener generates Warning when no Theme Folder is chosen

### ISSUE THREAD

**Issue by tarun-uwe** [Netzhirsch/CookieOptInBundle#14]
If in theme settings no folder is chosen, the PageLayoutListener generates a warning.
Which makes it hard to use the Debug mode.

It is happening here as there is added a Directory Separator. 
 https://github.com/Netzhirsch/CookieOptInBundle/blob/196d3031e1735b7b82c08198d9460add6f9420a2/src/EventListener/PageLayoutListener.php#L402-L407

Contao Version: 4.12.1
Netzhirsch CookieOptInBundle Version: 2.7.14

### Double Slash - no Theme folder is chosen
- ![image](https://user-images.githubusercontent.com/30664429/132351412-6f28cb98-25ce-4db3-bac6-1c531b6f3630.png)

### No double Slash - if a **sub**directory is chosen.
- ![image](https://user-images.githubusercontent.com/30664429/132353114-3cceb4f6-c16a-4128-b302-4b8beb853d69.png)

**Comment by luhmannAlexander** [comment]
Danke für die ausführliche Meldung. Ist mit Version 2.7.18 behoben.
