### ISSUE TITLE
Module CookieOptIn kann nicht gespeichert werden

### ISSUE THREAD

**Issue by tarun-uwe** [Netzhirsch/CookieOptInBundle#16]
Nach dem Update lassen sich bestehende und auch neue Module nicht mehr speichern.
Im Install Tool sind keine DB Änderungen angegeben.

Der Fehlermeldung nach sollen die Werte in tl_module gespeichert werden, aber angedacht ist denke ich tl_ncoi_cookie

![image](https://user-images.githubusercontent.com/30664429/135980977-296a8711-c6e4-4cf0-88eb-71d5049ab46e.png)

![image](https://user-images.githubusercontent.com/30664429/135981049-1672d35e-62cd-41ef-942b-1828f4078b79.png)

**Comment by luhmannAlexander** [comment]
Danke für die Meldung @tarun-uwe.
Die Daten sollen wie vermutet in die Tabelle "tl_ncoi_cookie" damit die "tl_module" Tabelle nicht zu voll wird. Ab mehr als 50 Spalten gab es bei einigen unser Kunden Probleme. 
Leider konnte ich das Problem noch nicht nachstellen. 
Hat das lösches des Caches fehlerfrei funktioniert? Sollte automatisch mit dem Update passiert sein. 
Um welche Contao Version handelt es sich?

**Comment by tarun-uwe** [comment]
Hi @luhmannAlexander 
ich habe den Cache noch mal separat entfernt.

Es ist die Contao Version 4.12.1 und die Netzhirsch Version 2.7.18. Vor dem Update auf die 2.7.18 ging es mit der Version 2.7.15

Ich habe noch mal zurück auf 2.7.15 gewechselt, hier ließ sich ein neues Modul speichern - unter 2.7.18 aber wieder nicht.

**Comment by tarun-uwe** [comment]
> Hi @luhmannAlexander ich habe den Cache noch mal separat entfernt.
> 
> Es ist die Contao Version 4.12.1 und die Netzhirsch Version 2.7.18. Vor dem Update auf die 2.7.18 ging es mit der Version 2.7.15
> 
> Ich habe noch mal zurück auf 2.7.15 gewechselt, hier ließ sich ein neues Modul speichern - unter 2.7.18 aber wieder nicht.

Ich habe auch noch eine andere Installation auf 4.12.1 und 2.7.18 geupdatet und auch hier ist der Fehler vorhanden.

**Comment by luhmannAlexander** [comment]
Problem ist mit Version 2.7.19 gelöst. Danke für das Feedback.
