### ISSUE TITLE
console.log in NcoiTrack.js/NcoiTrack.min.js

### ISSUE THREAD

**Issue by RWesemann** [Netzhirsch/CookieOptInBundle#18]
Servus,
hat das einen Grund, dass im Release noch "console.log" enthalten ist? Wird mir auf der produktiven Seite ausgegeben, 

https://github.com/Netzhirsch/CookieOptInBundle/blob/942c6b076a84cabfea964536d80728bc07d27c5d/src/Resources/public/js/NcoiTrack.js#L22

**Comment by luhmannAlexander** [comment]
Danke für den Hinweis. War nur zum debuggen, haben wir wieder entfernt.

Ebenfalls haben wir auch alle JS-Datein neu minimiert.
