### ISSUE TITLE
Probleme beim Speichern der Seiten Impressum und Datenschutz

### ISSUE THREAD

**Issue by toccamonium-fe** [Netzhirsch/CookieOptInBundle#2]
Hallo,

wir benutzen die aktuelle Version 1.2.12 und haben hier im Modul Cookie-Bar das Problem, dass er die Seiten für Impressum und Datenschutz nicht korrekt abspeichert. 
Unser Contao BE besteht aus vielen Seitenbäumen und hier tritt das Phänomen auf. Bei einem Seitenbaum klappte die Zuweisung problemlos.

**Comment by Netzhirsch** [comment]
Hallo @toccamonium-fe,

das Problem sollte nun mit dem neuen Release 1.2.13 behoben sein. Können Sie das bestätigen?
