### ISSUE TITLE
Fehler in PageLayoutListener

### ISSUE THREAD

**Issue by tarun-uwe** [Netzhirsch/CookieOptInBundle#4]
Liebes Netzhirsch Team,

wir bekommen in einer frischen Installation folgende Warnung:

`Warning: count(): Parameter must be an array or an object that implements Countable`

hervorgerufen durch

https://github.com/Netzhirsch/CookieOptInBundle/blob/da148a53fd0b0a433981791f2eebaa5847519a41/src/EventListener/PageLayoutListener.php#L73

Diese Problem erscheint bei einer Contao 4.4 und Contao 4.9 Installation.

Die Count Warnung habe ich umgangen durch ein hinzufügen von 
`$tlCookieIds = [];` am Start von **onGetPageLayoutListener**

Durch gab es einen weiteren Fehler in
https://github.com/Netzhirsch/CookieOptInBundle/blob/da148a53fd0b0a433981791f2eebaa5847519a41/src/EventListener/PageLayoutListener.php#L95

welchen ich durch `(!is_array($cookieGroups[0]) && !is_null($cookieGroups))` in Zeile 92 gelöst habe.

Ich sehe hier ein generelles Problem in der Funktion. Wenn ich eine Multi Domain Installation habe, würde diese immer durchlaufen werden, auch für Domains, die gar nicht das Bundle nutzen sollen.

Viele Grüße
Uwe Tarun

**Comment by Netzhirsch** [comment]
Hallo Uwe,

vielen Dank für die Hinweise und die Ideen. Wir befinden uns diesbezüglich bereits in der Umsetzung und werden diese im nächsten Release implementieren. Dies gilt auch für das Feature in Issue #5.

Viele Grüße
Christoph Wittstock
