### ISSUE TITLE
Konflikt mit "Custom Elements"

### ISSUE THREAD

**Issue by tonsinn** [Netzhirsch/CookieOptInBundle#6]
Hallo netzhirsch-Team,

wir mussten feststellen, dass `netzhirsch/cookie-opt-in-bundle` sich nicht mit `madeyourday/contao-rocksolid-custom-elements` verträgt. Nach jedem Contao-Update sind einige Frontend-Module nicht mehr im Contao Backend konfigurierbar.

Vom Entwickler der "Custom Elements" erhielten wir folgenden Hinweis:
Die Erweiterung `netzhirsch/cookie-opt-in-bundle` überschreibt zum Beispiel in der Datei *vendor/netzhirsch/cookie-opt-in-bundle/src/Resources/contao/dca/tl_module.php* auf Zeile 92 alle `onload_callbacks` anderer Erweiterungen die vor dem Cookie-Bundle geladen werden:

```
$GLOBALS['TL_DCA']['tl_module']['config']['onload_callback'] = [['tl_module_ncoi','setCookieGroups']];
```

Richtig wäre den callback hinzuzufügen anstatt zu überschreiben:

```
$GLOBALS['TL_DCA']['tl_module']['config']['onload_callback'][] = ['tl_module_ncoi','setCookieGroups'];
```

**Comment by Netzhirsch** [comment]
Hallo adera-web,

Dieses Problem haben wir bereits in Release 2.1.1 behoben. Bitte updaten.

Liebe Grüße 
Der Netzhirsch
