### ISSUE TITLE
Artikel lassen sich nicht mehr im Contao bearbeiten

### ISSUE THREAD

**Issue by tonsinn** [Netzhirsch/CookieOptInBundle#8]
Netzhirsch\CookieOptInBundle\EventListener\PageLayoutListener::shouldRemoveModules() must be an instance of Contao\PageModel, null given, called in /www/htdocs/w0197110/generationen-vorsorge.de/vendor/netzhirsch/cookie-opt-in-bundle/src/EventListener/ParseFrontendTemplateListener.php on line 28

erhalte ich, wenn ich im Contao 4.10.4 einen Artikel zur Bearbeitung öffnen möchte. Ich habe im Contao Manager die Aktualisierung frisch durchgeführt. Netzhirsch Version 2.4.7

**Comment by Peresics** [comment]
Das selbe bei uns auch. Editieren mit der gleichen Fehlermeldung nicht mehr möglich.

**Comment by tonsinn** [comment]
mit Update auf 2.4.8. ist das Problem gelöst. Danke für die schnelle Fehlerbehebung.

**Comment by luhmannAlexander** [comment]
Danke für die Hinweise.
