### ISSUE TITLE
netzhirschCookieOptIn.css (u. a.)wird immer neu erzeugt

### ISSUE THREAD

**Issue by c4y** [Netzhirsch/CookieOptInBundle#9]
In der ModuleCookieOptInBar.php in Zeile 206 wird ein falscher Pfad geprüft. Dadurch wird die CSS Datei jedesmal neu erzeugt. Kann es sein, dass es dirname(__DIR__,7) heißen muss und nicht dirname(__DIR__,5)?

**Comment by luhmannAlexander** [comment]
Die Erstellung der CSS Datei findet in der Klasse [Helper](https://github.com/Netzhirsch/CookieOptInBundle/blob/master/src/Resources/contao/classes/Helper.php) statt. Im Pfad vendor/netzhirsch/cookie-opt-in-bundlesrc/Resources/contao/classes/Helper.php . 

dirname(__DIR__) führt  zu /var/www/html/netzhirsch.de/vendor/netzhirsch/cookie-opt-in-bundle/src/Resources/contao.
Hier muss nun 6 Verzeichniss hochgegangen werden. Dabei fängt dirname erst bei Level 2 an ein Verzeichniss hochzugehen, damit kommt es zu dirname(__DIR__,7).

**Comment by c4y** [comment]
Gibt es da keinen Commit zu? Oder ist das jetzt nicht als Fehler anerkannt worden? Aktuell wird die CSS Datei jedesmal neu erzeugt. Im aktuellen Projekt sind das in zwei Wochen >300 GB...

**Comment by luhmannAlexander** [comment]
Das ist ein Problem ist mit der Version 2.1.0 behoben https://github.com/Netzhirsch/CookieOptInBundle/tree/2.1.0.
Bitte Update ausführen.
